
module.exports = {
  PARSE_APP_ID: 'uoVDvekxzKVrPay12PR9rFhMk18xSiXjUFJRQ893',
  PARSE_REST_API_KEY: 'KaDTOFik6e2Zk94wVKkyNxahWCHdL9muzOFLoqr7',
  PARSE_MASTER_KEY: 'bluFBl60CLGzETiJwR9waTopacxz9X6KXAuuPEnY'
};